// Per-lead flags you set by hand, layered on top of the scraped leads.json.
//
// leads.json is regenerated by the pipeline on every run and carries no stable
// id, so flags are keyed by a fingerprint of the fields that identify a real
// business (label + city + phone). A re-scrape of the same clinic keeps its
// flag; a genuinely different lead gets a different key.
//
// Why "doesn't exist" specifically: Apollo, Maps and OSM all return listings
// for businesses that have closed, moved, or were never real. Those leads
// otherwise resurface every single run and get re-dialled, which wastes the
// free-tier email unlocks and, worse, wastes calls.

export type LeadFlag = "missing"; // "doesn't exist" / bad listing

export type LeadFlags = Record<string, LeadFlag>;

const KEY = "revengine.command-center.leadflags.v1";

/** Stable fingerprint for a lead across re-scrapes.
 *
 * Deliberately label + city + phone, and deliberately NOT website. Website is
 * the least stable field across sources: OSM routinely omits it where Maps
 * supplies it, so including it gives the same clinic two different keys on two
 * runs and its flag silently stops applying. That failure is common and
 * defeats the whole point.
 *
 * The accepted cost is that two genuinely different listings sharing a name and
 * city with no phone on either collide, and flagging one hides both. That is
 * rarer, and losing one lead beats re-dialling a dead one every run.
 */
export function leadKey(l: { label?: string; city?: string; phone?: string }): string {
  const norm = (s?: string) => (s || "").trim().toLowerCase().replace(/\s+/g, " ");
  const digits = (s?: string) => (s || "").replace(/\D/g, "");
  return [norm(l.label), norm(l.city), digits(l.phone)].join("|");
}

export const leadFlagStore = {
  load(): LeadFlags {
    if (typeof window === "undefined") return {};
    try {
      const raw = window.localStorage.getItem(KEY);
      if (!raw) return {};
      const parsed: unknown = JSON.parse(raw);
      // Validate rather than trusting the cast: this is a system boundary, and
      // an older or hand-edited shape would otherwise flow straight into render.
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};
      const out: LeadFlags = {};
      for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
        if (v === "missing") out[k] = "missing";
      }
      return out;
    } catch {
      // Corrupt or unavailable storage must not take the panel down with it.
      return {};
    }
  },
  save(flags: LeadFlags): void {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(KEY, JSON.stringify(flags));
    } catch {
      // Quota or private-mode failure. Losing a flag is survivable; throwing
      // inside a render path is not.
    }
  },
};
