// SAT GRIND data layer - a localStorage SM-2 spaced-repetition deck driving
// toward the SAT 1550 target (Aug 2026). Pure client-side, static-export safe:
// nothing here touches a network or a backend, mirroring lib/storage.ts.
//
// Two consumers read this module:
//   - components/SatGrind.tsx renders the drill and grades cards.
//   - the now.json feed (scripts/build_now.py) reports the `studying` half.
//     The tab persists a derived snapshot (nowStudyingBlock) to localStorage
//     and can download it as data/now-studying.json for the build script to
//     pick up - the only bridge between client state and the static feed.

import { isoDate } from "./day";

export const SAT_TARGET = 1550;
export const SAT_TEST_DATE = "2026-08"; // College Board August 2026 SAT

// SM-2 defaults.
const EASE_DEFAULT = 2.5;
const EASE_MIN = 1.3;

export type Subject = "math" | "reading" | "writing" | "vocab";

export interface Card {
  id: string;
  front: string;
  back: string;
  subject: Subject;
  /** SM-2 easiness factor (>= 1.3). */
  ease: number;
  /** current inter-repetition interval in days. */
  interval: number;
  /** number of successful repetitions in a row. */
  reps: number;
  /** YYYY-MM-DD the card is next due. */
  due: string;
  /** ISO timestamp of the last grade, or null if never reviewed. */
  lastReviewed: string | null;
  /** generated by the starter seed, not hand-added. */
  seeded?: boolean;
}

// Review log so streak / reviewed-today survive reloads without re-deriving
// from card timestamps (which lose per-day counts once a card is re-due).
export interface SatProgress {
  /** YYYY-MM-DD -> number of grades that day. */
  reviewsByDay: Record<string, number>;
  /** ISO timestamp of the most recent grade across all days. */
  lastSessionAt: string | null;
  /** free-text focus the user is grinding (drives now.json current_focus). */
  focus: string;
}

export interface SatState {
  cards: Card[];
  progress: SatProgress;
}

const KEY = "revengine.command-center.sat.v1";
// Mirror of the derived now.json `studying` block, refreshed on every grade so
// a build can read the latest without re-running SM-2 in Python.
const NOW_KEY = "revengine.command-center.sat.nowblock.v1";

// ── Starter deck ─────────────────────────────────────────────────────────────
// Seeded high-yield SAT cards across the four sections. Kept deliberately small;
// the user grows it. Ids are stable so progress survives a re-seed merge.
type SeedCard = Pick<Card, "id" | "front" | "back" | "subject">;

const SEED: SeedCard[] = [
  {
    id: "sat:m-slope",
    subject: "math",
    front: "Slope of a line through (x1,y1) and (x2,y2)?",
    back: "(y2 - y1) / (x2 - x1) - rise over run.",
  },
  {
    id: "sat:m-quadratic",
    subject: "math",
    front: "Quadratic formula for ax^2 + bx + c = 0?",
    back: "x = (-b +/- sqrt(b^2 - 4ac)) / 2a. Discriminant b^2 - 4ac sets the root count.",
  },
  {
    id: "sat:m-vertex",
    subject: "math",
    front: "Vertex of y = ax^2 + bx + c?",
    back: "x = -b/(2a); plug back in for y. Vertex form y = a(x-h)^2 + k has vertex (h,k).",
  },
  {
    id: "sat:m-special-triangle",
    subject: "math",
    front: "Side ratios of a 30-60-90 triangle?",
    back: "1 : sqrt(3) : 2 (opposite 30, 60, 90). A 45-45-90 is 1 : 1 : sqrt(2).",
  },
  {
    id: "sat:m-percent",
    subject: "math",
    front: "Percent change from old to new value?",
    back: "(new - old) / old x 100. A 20% rise then 20% fall is a net 4% loss.",
  },
  {
    id: "sat:m-exponent",
    subject: "math",
    front: "x^a * x^b and (x^a)^b ?",
    back: "x^(a+b) and x^(a*b). x^0 = 1; x^-a = 1/x^a.",
  },
  {
    id: "sat:w-semicolon",
    subject: "writing",
    front: "When does a semicolon join two clauses?",
    back: "Only when both sides are independent clauses (each a full sentence). Otherwise use a comma or nothing.",
  },
  {
    id: "sat:w-its",
    subject: "writing",
    front: "its vs it's?",
    back: "its = possessive (the dog wagged its tail). it's = it is / it has.",
  },
  {
    id: "sat:w-modifier",
    subject: "writing",
    front: "Fix for a dangling modifier?",
    back: "The noun right after the opening modifier must be the thing it describes. 'Running late, the bus left' is wrong - the bus wasn't running late.",
  },
  {
    id: "sat:r-tone",
    subject: "reading",
    front: "Reading: how to nail a tone/attitude question?",
    back: "Anchor to charged words in the passage, not your gut. Eliminate answers that are too extreme or unsupported by the text.",
  },
  {
    id: "sat:v-ambivalent",
    subject: "vocab",
    front: "ambivalent",
    back: "Having mixed or contradictory feelings about something. Not the same as indifferent.",
  },
  {
    id: "sat:v-pragmatic",
    subject: "vocab",
    front: "pragmatic",
    back: "Dealing with things practically rather than ideally; results-focused.",
  },
];

function seedCard(s: SeedCard, today: string): Card {
  return {
    ...s,
    ease: EASE_DEFAULT,
    interval: 0,
    reps: 0,
    due: today, // brand-new cards are due immediately
    lastReviewed: null,
    seeded: true,
  };
}

export function buildSeedDeck(today: string = isoDate()): Card[] {
  return SEED.map((s) => seedCard(s, today));
}

// ── Store ────────────────────────────────────────────────────────────────────
function emptyProgress(): SatProgress {
  return { reviewsByDay: {}, lastSessionAt: null, focus: "SAT math fundamentals" };
}

export const satStore = {
  load(): SatState {
    const today = isoDate();
    if (typeof window === "undefined") {
      return { cards: buildSeedDeck(today), progress: emptyProgress() };
    }
    try {
      const raw = window.localStorage.getItem(KEY);
      if (!raw) return { cards: buildSeedDeck(today), progress: emptyProgress() };
      const parsed = JSON.parse(raw) as Partial<SatState>;
      const cards = Array.isArray(parsed.cards) ? (parsed.cards as Card[]) : [];
      const progress = { ...emptyProgress(), ...(parsed.progress ?? {}) };
      // Merge in any new seed cards added since the user first loaded, keeping
      // their existing SM-2 state for cards they already have.
      const have = new Set(cards.map((c) => c.id));
      for (const s of SEED) {
        if (!have.has(s.id)) cards.push(seedCard(s, today));
      }
      return { cards, progress };
    } catch {
      return { cards: buildSeedDeck(today), progress: emptyProgress() };
    }
  },
  save(state: SatState): void {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(KEY, JSON.stringify(state));
      // Keep the now.json mirror current on every persist.
      window.localStorage.setItem(NOW_KEY, JSON.stringify(nowStudyingBlock(state)));
    } catch {
      /* private mode / quota - feed mirror just won't update */
    }
  },
};

// ── SM-2 ─────────────────────────────────────────────────────────────────────
// quality: 0 Again, 3 Hard, 4 Good, 5 Easy. Standard SuperMemo-2 update.
export type Grade = 0 | 3 | 4 | 5;

export function gradeCard(card: Card, quality: Grade, today: string = isoDate()): Card {
  let { ease, interval, reps } = card;

  if (quality < 3) {
    // lapse - restart the rep count, see it again tomorrow
    reps = 0;
    interval = 1;
  } else {
    if (reps === 0) interval = 1;
    else if (reps === 1) interval = 6;
    else interval = Math.round(interval * ease);
    reps += 1;
  }

  // EF update (SM-2): clamped at the 1.3 floor.
  ease = ease + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
  if (ease < EASE_MIN) ease = EASE_MIN;

  return {
    ...card,
    ease: Math.round(ease * 1000) / 1000,
    interval,
    reps,
    due: addDays(today, interval),
    lastReviewed: new Date().toISOString(),
  };
}

/** Record one grade in the progress log (reviewed-today + last session). */
export function logReview(progress: SatProgress, today: string = isoDate()): SatProgress {
  const reviewsByDay = { ...progress.reviewsByDay };
  reviewsByDay[today] = (reviewsByDay[today] ?? 0) + 1;
  return { ...progress, reviewsByDay, lastSessionAt: new Date().toISOString() };
}

// ── Derived selectors ────────────────────────────────────────────────────────
export function dueCards(cards: Card[], today: string = isoDate()): Card[] {
  return cards
    .filter((c) => c.due <= today)
    .sort((a, b) => a.due.localeCompare(b.due) || a.id.localeCompare(b.id));
}

export function reviewedToday(progress: SatProgress, today: string = isoDate()): number {
  return progress.reviewsByDay[today] ?? 0;
}

/** Consecutive days (ending today or yesterday) with >= 1 review. */
export function streakDays(progress: SatProgress, today: string = isoDate()): number {
  const days = progress.reviewsByDay;
  // Allow the streak to still count if today hasn't been touched yet.
  let cursor = days[today] ? today : addDays(today, -1);
  if (!days[cursor]) return 0;
  let streak = 0;
  while (days[cursor]) {
    streak += 1;
    cursor = addDays(cursor, -1);
  }
  return streak;
}

export function satTestDaysLeft(today: string = isoDate()): number {
  // Test date is a month bucket; anchor the countdown to the 1st.
  const target = new Date(SAT_TEST_DATE + "-01T00:00:00");
  const now = new Date(today + "T00:00:00");
  return Math.round((target.getTime() - now.getTime()) / 86_400_000);
}

// ── now.json bridge ──────────────────────────────────────────────────────────
export interface NowStudyingBlock {
  sat_target: number;
  sat_test_date: string;
  cards_due: number;
  cards_reviewed_today: number;
  streak_days: number;
  current_focus: string;
  last_session_at: string | null;
}

/** The `studying` half of now.json, derived purely from SM-2 state. */
export function nowStudyingBlock(state: SatState, today: string = isoDate()): NowStudyingBlock {
  return {
    sat_target: SAT_TARGET,
    sat_test_date: SAT_TEST_DATE,
    cards_due: dueCards(state.cards, today).length,
    cards_reviewed_today: reviewedToday(state.progress, today),
    streak_days: streakDays(state.progress, today),
    current_focus: state.progress.focus || "SAT prep",
    last_session_at: state.progress.lastSessionAt,
  };
}

// ── date helper (UTC-free, mirrors lib/day.ts isoDate) ───────────────────────
export function addDays(iso: string, days: number): string {
  const d = new Date(iso + "T00:00:00");
  d.setDate(d.getDate() + days);
  return isoDate(d);
}
