// SAT GRIND data layer - a localStorage FSRS-4.5 spaced-repetition deck driving
// toward the SAT 1550 target (Aug 2026). Pure client-side, static-export safe:
// nothing here touches a network or a backend, mirroring lib/storage.ts.
//
// Why FSRS over textbook SM-2 (the old scheduler): SM-2 resets the interval to 1
// day on any lapse (wasting reviews) and drifts about 16 percent from a retention
// target. FSRS-4.5 with fixed default weights is deterministic, needs no training
// or backend, hits a 90 percent target within about 5 percent, and is what Anki
// 23.10 ships. The whole scheduler is the pure function gradeCard() below.
//
// Three learning levers are baked in here, each grounded in the cited research:
//   - Spaced repetition (Dunlosky 2013 HIGH-utility): FSRS schedules each card as
//     its recall probability decays.
//   - The spacing effect (Cepeda 2006): requestRetention tapers UP under 30 days
//     and every interval is clamped to the test date, so the countdown shapes the
//     schedule instead of being cosmetic.
//   - Interleaving (Rohrer and Taylor 2007): dueCards() emits subjects round-robin
//     (and rotates math by skill) so the queue mixes instead of blocking.
//
// Two consumers read this module:
//   - components/SatGrind.tsx renders the drill and grades cards.
//   - the now.json feed (scripts/build_now.py) reports the `studying` half.
//     The tab persists a derived snapshot (nowStudyingBlock) to localStorage
//     and can download it as data/now-studying.json for the build script to
//     pick up - the only bridge between client state and the static feed.

import { isoDate } from "./day";

export const SAT_TARGET = 1550;
export const SAT_TEST_DATE = "2026-08"; // College Board August 2026 SAT

export type Subject = "math" | "reading" | "writing" | "vocab";

export interface Card {
  id: string;
  front: string;
  back: string;
  subject: Subject;
  /** FSRS memory stability in days (expected interval at requestRetention). */
  stability: number;
  /** FSRS difficulty, clamped 1..10. */
  difficulty: number;
  /** current inter-repetition interval in days (derived from stability). */
  interval: number;
  /** YYYY-MM-DD the card is next due. */
  due: string;
  /** ISO timestamp of the last grade, or null if never reviewed. */
  lastReviewed: string | null;
  /** finer math discrimination so the math bucket can rotate by skill type. */
  skill?: string;
  /** optional elaboration shown on reveal (elaborative interrogation). */
  why?: string;
  /** last few confidence-vs-outcome pairs (metacognitive calibration), capped. */
  calibration?: { predicted: "sure" | "unsure"; correct: boolean }[];
  /** generated by the starter seed, not hand-added. */
  seeded?: boolean;
}

// Review log so streak / reviewed-today survive reloads without re-deriving
// from card timestamps (which lose per-day counts once a card is re-due).
export interface SatProgress {
  /** YYYY-MM-DD -> number of grades that day. */
  reviewsByDay: Record<string, number>;
  /** YYYY-MM-DD -> first-attempt retrieval success vs total attempts. */
  recallByDay: Record<string, { correct: number; attempted: number }>;
  /** ISO timestamp of the most recent grade across all days. */
  lastSessionAt: string | null;
  /** free-text focus the user is grinding (drives now.json current_focus). */
  focus: string;
}

export interface SatState {
  cards: Card[];
  progress: SatProgress;
}

const KEY = "revengine.command-center.sat.v2";
const LEGACY_KEY = "revengine.command-center.sat.v1"; // SM-2 era, migrated once
// Mirror of the derived now.json `studying` block, refreshed on every grade so
// a build can read the latest without re-running the scheduler in Python.
const NOW_KEY = "revengine.command-center.sat.nowblock.v1";

// ── FSRS-4.5 constants ───────────────────────────────────────────────────────
// Fixed default weights (no training, fully deterministic). Same vector Anki
// ships as the FSRS-4.5 preset.
const W = [
  0.4072, 1.1829, 3.1262, 15.4722, 7.2102, 0.5316, 1.0651, 0.0234, 1.616,
  0.1544, 1.0824, 1.9813, 0.0953, 0.2975, 2.2042, 0.2407, 2.9466, 0.5034,
  0.6567,
] as const;
const DECAY = -0.5;
const FACTOR = 19 / 81; // 0.2345679...
const BASE_RETENTION = 0.9;
const CRUNCH_RETENTION = 0.93; // tightened taper inside the final 30 days
const CRUNCH_WINDOW = 30; // days before the test where the taper engages

function clamp(x: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, x));
}

// ── Starter deck ─────────────────────────────────────────────────────────────
// Seeded high-yield SAT cards across the four sections. Kept deliberately small;
// the user grows it. Ids are stable so progress survives a re-seed merge. Math
// markup (x^2, sqrt(...), +/-) is rendered by <Math/> in the UI as real
// superscripts and radicals, so no raw carets are ever shown.
type SeedCard = Pick<
  Card,
  "id" | "front" | "back" | "subject" | "skill" | "why"
>;

const SEED: SeedCard[] = [
  {
    id: "sat:m-slope",
    subject: "math",
    skill: "lines",
    front: "Slope of a line through (x1,y1) and (x2,y2)?",
    back: "(y2 - y1) / (x2 - x1), rise over run.",
    why: "Slope is a rate of change; the subtraction order must match top and bottom or the sign flips.",
  },
  {
    id: "sat:m-quadratic",
    subject: "math",
    skill: "quadratics",
    front: "Quadratic formula for ax^2 + bx + c = 0?",
    back: "x = (-b +/- sqrt(b^2 - 4ac)) / 2a. Discriminant b^2 - 4ac sets the root count.",
    why: "It is the completed-square form solved for x, so it works on any quadratic the SAT can throw at you.",
  },
  {
    id: "sat:m-vertex",
    subject: "math",
    skill: "quadratics",
    front: "Vertex of y = ax^2 + bx + c?",
    back: "x = -b/(2a); plug back in for y. Vertex form y = a(x-h)^2 + k has vertex (h,k).",
    why: "The vertex sits on the axis of symmetry, which is exactly x = -b/(2a).",
  },
  {
    id: "sat:m-special-triangle",
    subject: "math",
    skill: "geometry",
    front: "Side ratios of a 30-60-90 triangle?",
    back: "1 : sqrt(3) : 2 (opposite 30, 60, 90). A 45-45-90 is 1 : 1 : sqrt(2).",
    why: "These come straight from the unit circle, so memorizing them skips the trig every time.",
  },
  {
    id: "sat:m-percent",
    subject: "math",
    skill: "percents",
    front: "Percent change from old to new value?",
    back: "(new - old) / old * 100. A 20% rise then 20% fall is a net 4% loss.",
    why: "The base is always the original value, which is why successive percent moves do not cancel.",
  },
  {
    id: "sat:m-exponent",
    subject: "math",
    skill: "exponents",
    front: "x^a * x^b and (x^a)^b ?",
    back: "x^(a+b) and x^(a*b). x^0 = 1; x^-a = 1/x^a.",
    why: "Multiplying powers adds exponents because you are concatenating the factors; nesting multiplies them.",
  },
  {
    id: "sat:w-semicolon",
    subject: "writing",
    skill: "punctuation",
    front: "When does a semicolon join two clauses?",
    back: "Only when both sides are independent clauses (each a full sentence). Otherwise use a comma or nothing.",
    why: "A semicolon is a soft period, so whatever sits on each side must survive as its own sentence.",
  },
  {
    id: "sat:w-its",
    subject: "writing",
    skill: "usage",
    front: "its vs it's?",
    back: "its = possessive (the dog wagged its tail). it's = it is / it has.",
    why: "Possessive pronouns never take an apostrophe; the apostrophe only ever marks the dropped letters of a contraction.",
  },
  {
    id: "sat:w-modifier",
    subject: "writing",
    skill: "modifiers",
    front: "Fix for a dangling modifier?",
    back: "The noun right after the opening modifier must be the thing it describes. 'Running late, the bus left' is wrong, the bus was not running late.",
    why: "A modifier attaches to the nearest noun, so the intended subject has to sit first or the sentence describes the wrong thing.",
  },
  {
    id: "sat:r-tone",
    subject: "reading",
    skill: "tone",
    front: "Reading: how to nail a tone/attitude question?",
    back: "Anchor to charged words in the passage, not your gut. Eliminate answers that are too extreme or unsupported by the text.",
    why: "SAT tone is always defensible from specific text, so the right answer is the moderate one the words actually license.",
  },
  {
    id: "sat:v-ambivalent",
    subject: "vocab",
    front: "ambivalent",
    back: "Having mixed or contradictory feelings about something. Not the same as indifferent.",
    why: "The root ambi- means both, so the word is about holding two feelings at once, not the absence of feeling.",
  },
  {
    id: "sat:v-pragmatic",
    subject: "vocab",
    front: "pragmatic",
    back: "Dealing with things practically rather than ideally; results-focused.",
    why: "It shares a root with practice, so it points at what works in action over what sounds good in theory.",
  },
];

function seedCard(s: SeedCard, today: string): Card {
  return {
    ...s,
    stability: 0,
    difficulty: 0,
    interval: 0,
    due: today, // brand-new cards are due immediately
    lastReviewed: null,
    seeded: true,
  };
}

export function buildSeedDeck(today: string = isoDate()): Card[] {
  return SEED.map((s) => seedCard(s, today));
}

// ── Store ────────────────────────────────────────────────────────────────────
function emptyProgress(): SatProgress {
  return {
    reviewsByDay: {},
    recallByDay: {},
    lastSessionAt: null,
    focus: "SAT math fundamentals",
  };
}

// One-time SM-2 -> FSRS migration. Old cards carried ease/interval/reps; we seed
// stability from the old interval (so a well-spaced card keeps its place) and
// difficulty at the 5 midpoint, then drop the SM-2 fields.
interface LegacyCard {
  id: string;
  front: string;
  back: string;
  subject: Subject;
  interval?: number;
  due?: string;
  lastReviewed?: string | null;
  seeded?: boolean;
}

function migrateLegacyCard(old: LegacyCard, today: string): Card {
  const seed = SEED.find((s) => s.id === old.id);
  const reviewed = old.lastReviewed ?? null;
  return {
    id: old.id,
    front: seed?.front ?? old.front,
    back: seed?.back ?? old.back,
    subject: old.subject,
    skill: seed?.skill,
    why: seed?.why,
    stability: reviewed ? Math.max(old.interval ?? 1, 1) : 0,
    difficulty: reviewed ? 5 : 0,
    interval: old.interval ?? 0,
    due: old.due ?? today,
    lastReviewed: reviewed,
    seeded: old.seeded,
  };
}

function mergeSeedInto(cards: Card[], today: string): Card[] {
  const have = new Set(cards.map((c) => c.id));
  for (const s of SEED) {
    if (!have.has(s.id)) cards.push(seedCard(s, today));
  }
  return cards;
}

export const satStore = {
  load(): SatState {
    const today = isoDate();
    if (typeof window === "undefined") {
      return { cards: buildSeedDeck(today), progress: emptyProgress() };
    }
    try {
      const raw = window.localStorage.getItem(KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as Partial<SatState>;
        const cards = Array.isArray(parsed.cards) ? (parsed.cards as Card[]) : [];
        const progress = { ...emptyProgress(), ...(parsed.progress ?? {}) };
        return { cards: mergeSeedInto(cards, today), progress };
      }
      // No v2 store yet: try a one-time migration from the SM-2 era.
      const legacyRaw = window.localStorage.getItem(LEGACY_KEY);
      if (legacyRaw) {
        const legacy = JSON.parse(legacyRaw) as {
          cards?: LegacyCard[];
          progress?: Partial<SatProgress>;
        };
        const cards = Array.isArray(legacy.cards)
          ? legacy.cards.map((c) => migrateLegacyCard(c, today))
          : [];
        const progress = { ...emptyProgress(), ...(legacy.progress ?? {}) };
        const migrated = { cards: mergeSeedInto(cards, today), progress };
        satStore.save(migrated); // persist under v2 so we only migrate once
        return migrated;
      }
      return { cards: buildSeedDeck(today), progress: emptyProgress() };
    } catch {
      return { cards: buildSeedDeck(today), progress: emptyProgress() };
    }
  },
  save(state: SatState): void {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(KEY, JSON.stringify(state));
      // Keep the now.json mirror current on every persist.
      window.localStorage.setItem(NOW_KEY, JSON.stringify(nowStudyingBlock(state)));
    } catch {
      /* private mode / quota - feed mirror just won't update */
    }
  },
};

// ── FSRS-4.5 scheduler ───────────────────────────────────────────────────────
// Grade buttons map to FSRS ratings: 1 Again, 2 Hard, 3 Good, 4 Easy.
export type Grade = 1 | 2 | 3 | 4;

/** A grade counts as a successful retrieval for stats unless it was Again. */
export function isRecallSuccess(g: Grade): boolean {
  return g >= 2;
}

/**
 * Desired retention for a given day. Base 0.9, tapering UP toward 0.93 inside
 * the final 30 days so the deck deliberately tightens before the test
 * (a desirable-difficulty taper). Past the test it pins to the crunch value.
 */
export function requestRetentionFor(today: string = isoDate()): number {
  const left = satTestDaysLeft(today);
  if (left >= CRUNCH_WINDOW) return BASE_RETENTION;
  if (left <= 0) return CRUNCH_RETENTION;
  const t = (CRUNCH_WINDOW - left) / CRUNCH_WINDOW; // 0..1 as the test nears
  return BASE_RETENTION + (CRUNCH_RETENTION - BASE_RETENTION) * t;
}

/** True while the requestRetention taper is active (final 30 days). */
export function crunchMode(today: string = isoDate()): boolean {
  const left = satTestDaysLeft(today);
  return left >= 0 && left < CRUNCH_WINDOW;
}

function initialStability(g: Grade): number {
  return Math.max(W[g - 1], 0.1);
}

function initialDifficulty(g: Grade): number {
  return clamp(W[4] - Math.exp(W[5] * (g - 1)) + 1, 1, 10);
}

function nextDifficulty(d: number, g: Grade): number {
  const d0Easy = W[4] - Math.exp(W[5] * 3) + 1; // difficulty if rated Easy
  const delta = d - W[6] * (g - 3); // linear nudge by grade
  return clamp(W[7] * d0Easy + (1 - W[7]) * delta, 1, 10);
}

function retrievability(elapsed: number, stability: number): number {
  return Math.pow(1 + (FACTOR * elapsed) / stability, DECAY);
}

function stabilityOnSuccess(d: number, s: number, r: number, g: Grade): number {
  const hardPenalty = g === 2 ? W[15] : 1;
  const easyBonus = g === 4 ? W[16] : 1;
  return (
    s *
    (1 +
      Math.exp(W[8]) *
        (11 - d) *
        Math.pow(s, -W[9]) *
        (Math.exp(W[10] * (1 - r)) - 1) *
        hardPenalty *
        easyBonus)
  );
}

function stabilityOnLapse(d: number, s: number, r: number): number {
  return (
    W[11] *
    Math.pow(d, -W[12]) *
    (Math.pow(s + 1, W[13]) - 1) *
    Math.exp(W[14] * (1 - r))
  );
}

function intervalFromStability(s: number, retention: number): number {
  // Invert R = (1 + FACTOR * t / S)^DECAY for t at the desired retention.
  return (s / FACTOR) * (Math.pow(retention, 1 / DECAY) - 1);
}

export function gradeCard(card: Card, g: Grade, today: string = isoDate()): Card {
  const firstReview = card.lastReviewed === null || card.stability <= 0;

  let stability: number;
  let difficulty: number;

  if (firstReview) {
    stability = initialStability(g);
    difficulty = initialDifficulty(g);
  } else {
    const elapsed = Math.max(
      0,
      daysBetween(isoDate(new Date(card.lastReviewed as string)), today),
    );
    const r = retrievability(elapsed, card.stability);
    difficulty = nextDifficulty(card.difficulty, g);
    stability =
      g === 1
        ? stabilityOnLapse(difficulty, card.stability, r)
        : stabilityOnSuccess(difficulty, card.stability, r, g);
  }

  stability = Math.max(stability, 0.1);

  // Spacing-effect levers: tighten retention near the test, and never schedule a
  // card past the test date so the TEST IN countdown actually shapes the deck.
  const retention = requestRetentionFor(today);
  const maxInterval = Math.max(1, satTestDaysLeft(today));
  const interval = clamp(
    Math.round(intervalFromStability(stability, retention)),
    1,
    maxInterval,
  );

  return {
    ...card,
    stability: Math.round(stability * 1000) / 1000,
    difficulty: Math.round(difficulty * 1000) / 1000,
    interval,
    due: addDays(today, interval),
    lastReviewed: new Date().toISOString(),
  };
}

/** Append a confidence/outcome pair to a card, capped at the last 5. */
export function recordCalibration(
  card: Card,
  predicted: "sure" | "unsure",
  correct: boolean,
): Card {
  const log = [...(card.calibration ?? []), { predicted, correct }].slice(-5);
  return { ...card, calibration: log };
}

/** Record one grade + first-attempt retrieval outcome in the progress log. */
export function logReview(
  progress: SatProgress,
  success: boolean,
  today: string = isoDate(),
): SatProgress {
  const reviewsByDay = { ...progress.reviewsByDay };
  reviewsByDay[today] = (reviewsByDay[today] ?? 0) + 1;

  const recallByDay = { ...progress.recallByDay };
  const cell = recallByDay[today] ?? { correct: 0, attempted: 0 };
  recallByDay[today] = {
    correct: cell.correct + (success ? 1 : 0),
    attempted: cell.attempted + 1,
  };

  return {
    ...progress,
    reviewsByDay,
    recallByDay,
    lastSessionAt: new Date().toISOString(),
  };
}

// ── Derived selectors ────────────────────────────────────────────────────────

// Round-robin a list of cards by a key so consecutive items differ where
// possible (used to interleave subjects, and skills within math).
function roundRobin<T>(items: T[], keyOf: (it: T) => string): T[] {
  const buckets = new Map<string, T[]>();
  for (const it of items) {
    const k = keyOf(it);
    if (!buckets.has(k)) buckets.set(k, []);
    buckets.get(k)!.push(it);
  }
  const queues = [...buckets.values()];
  const out: T[] = [];
  let drained = false;
  while (!drained) {
    drained = true;
    for (const q of queues) {
      const next = q.shift();
      if (next !== undefined) {
        out.push(next);
        drained = false;
      }
    }
  }
  return out;
}

/**
 * Due cards, interleaved. Due-ness is the hard gate (a not-due card is never
 * surfaced just to mix). Within the gate, cards are emitted round-robin across
 * subjects, and the math bucket is itself rotated by skill, so the visible queue
 * alternates MATH/READING/WRITING/VOCAB instead of blocking by subject.
 */
export function dueCards(cards: Card[], today: string = isoDate()): Card[] {
  const due = cards
    .filter((c) => c.due <= today)
    .sort((a, b) => a.due.localeCompare(b.due) || a.id.localeCompare(b.id));

  const bySubject = new Map<Subject, Card[]>();
  for (const c of due) {
    if (!bySubject.has(c.subject)) bySubject.set(c.subject, []);
    bySubject.get(c.subject)!.push(c);
  }
  // Rotate math by skill for finer discriminative contrast.
  const math = bySubject.get("math");
  if (math) bySubject.set("math", roundRobin(math, (c) => c.skill ?? "_"));

  // Flatten subject buckets then round-robin across subjects.
  const flat: Card[] = [];
  for (const list of bySubject.values()) flat.push(...list);
  return roundRobin(flat, (c) => c.subject);
}

export function reviewedToday(progress: SatProgress, today: string = isoDate()): number {
  return progress.reviewsByDay[today] ?? 0;
}

/** Rolling first-attempt retrieval-success rate over the last 7 days (0..1), or null. */
export function recallRate(progress: SatProgress, today: string = isoDate()): number | null {
  let correct = 0;
  let attempted = 0;
  for (let i = 0; i < 7; i++) {
    const cell = progress.recallByDay[addDays(today, -i)];
    if (cell) {
      correct += cell.correct;
      attempted += cell.attempted;
    }
  }
  return attempted ? correct / attempted : null;
}

/** Consecutive days (ending today or yesterday) with >= 1 review. */
export function streakDays(progress: SatProgress, today: string = isoDate()): number {
  const days = progress.reviewsByDay;
  // Allow the streak to still count if today hasn't been touched yet.
  let cursor = days[today] ? today : addDays(today, -1);
  if (!days[cursor]) return 0;
  let streak = 0;
  while (days[cursor]) {
    streak += 1;
    cursor = addDays(cursor, -1);
  }
  return streak;
}

export function satTestDaysLeft(today: string = isoDate()): number {
  // Test date is a month bucket; anchor the countdown to the 1st.
  const target = new Date(SAT_TEST_DATE + "-01T00:00:00");
  const now = new Date(today + "T00:00:00");
  return Math.round((target.getTime() - now.getTime()) / 86_400_000);
}

// ── now.json bridge ──────────────────────────────────────────────────────────
export interface NowStudyingBlock {
  sat_target: number;
  sat_test_date: string;
  cards_due: number;
  cards_reviewed_today: number;
  streak_days: number;
  recall_rate_7d: number | null;
  current_focus: string;
  last_session_at: string | null;
}

/** The `studying` half of now.json, derived purely from scheduler state. */
export function nowStudyingBlock(state: SatState, today: string = isoDate()): NowStudyingBlock {
  const rate = recallRate(state.progress, today);
  return {
    sat_target: SAT_TARGET,
    sat_test_date: SAT_TEST_DATE,
    cards_due: dueCards(state.cards, today).length,
    cards_reviewed_today: reviewedToday(state.progress, today),
    streak_days: streakDays(state.progress, today),
    recall_rate_7d: rate === null ? null : Math.round(rate * 100) / 100,
    current_focus: state.progress.focus || "SAT prep",
    last_session_at: state.progress.lastSessionAt,
  };
}

// ── date helpers (UTC-free, mirrors lib/day.ts isoDate) ──────────────────────
export function addDays(iso: string, days: number): string {
  const d = new Date(iso + "T00:00:00");
  d.setDate(d.getDate() + days);
  return isoDate(d);
}

function daysBetween(fromISO: string, toISO: string): number {
  const a = new Date(fromISO + "T00:00:00");
  const b = new Date(toISO + "T00:00:00");
  return Math.round((b.getTime() - a.getTime()) / 86_400_000);
}
