export type Lane = "brand" | "leads" | "ops";

export interface Task {
  id: string;
  title: string;
  lane: Lane;
  done: boolean;
  /** ISO timestamp the task was created */
  createdAt: string;
  /** YYYY-MM-DD — the day this task appears under "Today" */
  dueDate: string;
  note?: string;
  /** true when generated by the daily seed, not hand-added */
  seeded?: boolean;
  /** true when carried forward from a previous, unfinished day */
  rolledOver?: boolean;
}

export const LANES: { id: Lane; label: string; accent: string }[] = [
  { id: "brand", label: "BRAND", accent: "var(--color-burgundy-bright)" },
  { id: "leads", label: "LEADS", accent: "var(--color-indigo)" },
  { id: "ops", label: "OPS", accent: "var(--color-cream-dim)" },
];
